#ifndef STARKWARE_ALGEBRA_FFT_MULTIPLICATIVE_GROUP_ORDERING_H_
#define STARKWARE_ALGEBRA_FFT_MULTIPLICATIVE_GROUP_ORDERING_H_

namespace starkware {

/*
  A cyclic multiplicative group generated by w can be enumerated in various ways.
  For our purpose, the interesting ones are:
  * Natural order - [1, w, w^2, w^3, ...]
  * Bit-reversed order - [1, -1, w^{N/4}, -w^{N/4}, ...] =
                         [w^{bitrev(0)}, w^{bitrev(1)},w^{bitrev(2)}, ...]

  Different FFT implementations have different ordering requirements on the polynomial evaluations.
  This enum is used to indicate which one is expected.

  Note that polynomial evaluations are the output/input of an FFT/IFFT, respectively.
  Since in-place radix2 FFT implementations have the side effect of bit-reversal permutation,
  the order of polynomial coefficients (an IFFT output) will typically be the dual order of the
  evaluation's order (and vice versa for FFT).
*/
enum class MultiplicativeGroupOrdering { kNaturalOrder, kBitReversedOrder };

}  // namespace starkware

#endif  // STARKWARE_ALGEBRA_FFT_MULTIPLICATIVE_GROUP_ORDERING_H_
