#include <sys/resource.h>
#include <cstdio>

#include "gflags/gflags.h"
#include "glog/logging.h"
#include "gtest/gtest.h"

#include "starkware/utils/task_manager.h"

/*
  Running death tests with Valgrind might cause generation of valgrind core-dump files (dependant on
  environment variables). Invoking this function ensures no core-dumps are generated by those tests.
*/
void DisableCoreDump() {
  struct rlimit rlim {};

  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);
}

GTEST_API_ int main(int argc, char** argv) {
  // Disable valgrind core-dump.
  DisableCoreDump();

  // Initialize Google's flags, logging, and test libraries.
  testing::InitGoogleTest(&argc, argv);

  FLAGS_n_threads = 4;  // Override default before parsing user provided arguments.

  gflags::ParseCommandLineFlags(&argc, &argv, true);
  google::InitGoogleLogging(argv[0]);  // NOLINT
  return RUN_ALL_TESTS();
}
